### ISSUE TITLE
About ASHL Dataset

### ISSUE THREAD

**Issue by Haoyu-ha** [llv22/tol_gui_region_detection#1]
Hi,

Could you please provide the download URL for the ASHL dataset?

Thanks.

**Comment by llv22** [comment]
@Haoyu-ha In order to decouple our published dataset and LoT model, this project serves as a submodule tol_gui_region_detection. So go to https://github.com/eric-ai-lab/Screen-Point-and-Read and git clone the whole project, then use git lfs pull to fetch all data. Currently,  we only upload ASHL and mobile trajectory verification data. you should find ASHL under data/screendata and training/validation json files are located at data/ScreenReaderData_train.json and data/ScreenReaderData_val.json enjoy it

**Comment by llv22** [comment]
@Haoyu-ha as storage limitation, we migrate our three datasets to huggingface. please follow the guide https://github.com/eric-ai-lab/Screen-Point-and-Read/tree/main/data to prepare you local datasets. As mentioned before, the ScreenPR's annotation data is still under verification. We may upload it later.  @UeFan

**Comment by llv22** [comment]
as we already provided the download link, I closed it

**Comment by Haoyu-ha** [comment]
Thank you so much.

> as we already provided the download link, I closed it
